# Generated by Django 4.0.2 on 2022-02-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('ladder_points', models.IntegerField(blank=True, null=True)),
                ('projectv_points', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(blank=True)),
                ('teamA_score', models.IntegerField(blank=True, null=True)),
                ('teamB_score', models.IntegerField(blank=True, null=True)),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_team_A', to='main.team')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_team_B', to='main.team')),
            ],
        ),
    ]
