# Generated by Django 4.0.2 on 2022-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='compute',
            field=models.BooleanField(default=False),
        ),
    ]
