# Generated by Django 4.0.2 on 2022-02-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_match_compute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teamA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_team_A', to='main.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='teamB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_team_B', to='main.team'),
        ),
    ]
