# Generated by Django 4.0.2 on 2022-02-17 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fakematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakematch',
            name='computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fakematch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
