# Generated by Django 4.0.2 on 2022-02-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_fakematch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakematch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
