# Generated by Django 4.0.2 on 2022-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_fakematch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakematch',
            name='points_deduction',
        ),
        migrations.AddField(
            model_name='fakematch',
            name='points_deduction_is_multiplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fakematch',
            name='points_deduction_is_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fakematch',
            name='points_deduction_muliplier',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
