# Generated by Django 4.0.2 on 2022-02-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_fakematch_points_deduction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakematch',
            old_name='points_deduction_muliplier',
            new_name='points_deduction_multiplier',
        ),
    ]
