# Generated by Django 4.0.2 on 2022-02-28 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_points_deduction_muliplier_fakematch_points_deduction_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_game',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
