# Generated by Django 4.0.2 on 2022-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teamA_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='teamB_score',
            field=models.IntegerField(default=0),
        ),
    ]
