# Generated by Django 4.0.2 on 2022-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_pointsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsystem',
            name='algo',
            field=models.BooleanField(default=False),
        ),
    ]
