# Generated by Django 4.0.2 on 2022-03-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pointsystem_algo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('rounds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.round')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stage')),
            ],
        ),
    ]
