# Generated by Django 4.0.2 on 2022-03-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_round_matches_remove_stage_rounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
