# Generated by Django 4.0.2 on 2022-03-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_round_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='round',
            new_name='stage',
        ),
    ]
