# Generated by Django 4.0.2 on 2022-03-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_result_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laddermatch',
            name='teamA_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='laddermatch',
            name='teamB_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
