# Generated by Django 4.0.2 on 2022-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_laddermatch_teama_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsystem',
            name='ladder_points_for_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointsystem',
            name='vrc_points_for_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointsystem',
            name='vrc_points_for_win',
            field=models.IntegerField(default=0),
        ),
    ]
