# Generated by Django 4.0.2 on 2022-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_pointsystem_ladder_points_for_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ladder_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ladder_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
