# Generated by Django 4.0.2 on 2022-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_team_ladder_loss_team_ladder_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsystem',
            name='recalculate_ladder',
            field=models.BooleanField(default=False),
        ),
    ]
